version: '2'
services:
 kex:
   image: cycloneproject/entrancedemo-kex
   build: components/KEX
   ports:
      - "20001:20001"
   volumes:
      - ./data/kex:/root/.kex 
  
 frontend:
   image: cycloneproject/entrancedemo-frontend
   build: components/Frontend

   ports:
      - "20000:20000" 
   volumes:
      - ./data/entrance:/root/.entrance
      - ./components/Frontend/config:/Entrance-PJ/Entrance-UM/src/config 
